### ISSUE TITLE
Support for "oneOf"

### ISSUE THREAD

**Issue by mhogerheijde** [bootprint/bootprint-json-schema#18]
When generating documentation for a schema that contains a type defined with `oneOf`, there is no documentation generated for those possible items from the `oneOf` definition.

Given the following schema:

```
{
  "title": "Example json-schema: oneOf where the elements are references.",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "This schema has two properties: a type that is defined by 'oneOf', where the items within are references to other types.",
  "properties": {
    "oneOfWithReferences" : {
      "description": "Some type, that can be one of 2 different types, defined by a reference.",
      "oneOf": [
        { "$ref": "#/definitions/one" },
        { "$ref": "#/definitions/two" }
      ]
    },
    "oneOfInline" : {
      "description": "Some type, that can be one of 2 different types, defined in-line",
      "oneOf": [
        { "type": "string" },
        { "type": "number" }
      ]
    }
  },
  "definitions": {
    "one" : {
      "description": "Number one of the types that `oneOfWithReferences` is allowed to be",
      "type": "string" },
    "two" : {
      "description": "Number two of the types that `oneOfWithReferences` is allowed to be",
      "type": "number"
    }
  }
}

```

When running

```
$ bootprint json-schema filename-of-schema-above.json out
Loading bootprint-json-schema 1.1.0
Loading bootprint-base 1.1.0
[ 'out/index.html',
  'out/main.css',
  'out/main.css.map',
  'out/bundle.js',
  'out/bundle.js.map' ]
```

When opening `index.html` in a browser; I see the following:

![screenshot from 2018-03-30 16-02-01](https://user-images.githubusercontent.com/1466140/38140382-c2ffba7c-3433-11e8-9e5c-796dfc1aa60e.png)

-------------------------------------------

Expected:

The types `oneOfWithReferences` and `oneOfInline` should have a list of possible subtypes. For `oneOfInline` you'd expect the sub-types to be rendered "in line" if possible. For `oneOfWithReferences` you'd expect a list of links to the allowed sub-types.

**Comment by nknapp** [comment]
That's true. It's probably because it wasn't allowed in swagger 2.0
You can either make a PR or try to use "bootprint@next" and "bootprint-json-schema@next", if you don't need swagger...

The only reason why the next-branch has not been merged yet, is that boot print to penapi@next" is not ready yet.

**Comment by mhogerheijde** [comment]
Thanks! I'll try out `@next` first; if that doesn't work, I'll try my way at creating a pull-request to support it.

**Comment by mhogerheijde** [comment]
@nknapp Confirmed! The `next` branch works as expected:

![screenshot from 2018-04-03 09-28-50](https://user-images.githubusercontent.com/1466140/38235444-860be0d2-3721-11e8-95c7-7644de8c170e.png)

Clicking the link scrolls to the definition.

Thanks a bunch!
