### ISSUE TITLE
Include Examples in the output

### ISSUE THREAD

**Issue by RyanHirsch** [bootprint/bootprint-json-schema#19]
I have [examples](http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.4) in my schema and would like them included in the output. Is this possible?

```json
{
  "title": "Metadata",
  "description": "Metadata about a piece of media and its status in the system",
  "type": "object",
  "properties": {
    "name": {
      "description":
        "The human readable name of the media. This defaults to the name of the file on the user file system when it was uploaded.",
      "type": "string",
      "examples": ["some-awesome-file.txt", "rick-roll.mp4"]
    }
  }
}
```

**Comment by nknapp** [comment]
The master branch and the `latest` version only support draft 04, which does not have examples. Please check out the `next`-branch, or install `bootprint-json-schema@next` for complete support of later drafts.
