### ISSUE TITLE
TypeError: qfs.isDirectory is not a function when using "develop" mode

### ISSUE THREAD

**Issue by puremourning** [bootprint/bootprint-json-schema#20]
### What I did:

Attempted to use `bootprint json-schema` in "developer" (watch) mode.

### Steps to repro:

Assuming you have a json file TEST.json:

* `npm install -g bootprint bootprint-json-schema`
* `bootprint json-schema ./TEST.json output/ -d`

### What I expected to happen:

File watcher starts, files are generated.

### What actually happens:

Crashes with `TypeError: qfs.isDirectory is not a function` within `customise-watch`.

### More details

There seems to be a complex dependency tree here, but reproduction is trivial.

Full stack trace is:

```
BenMBP:bootprint-json-schema ben$ bootprint json-schema ../bootprint/examples/content.yaml tmp/ -d
Loading bootprint-json-schema 1.1.0
Loading bootprint-base 1.1.0
Serving "tmp/" at http://127.0.0.1:8181
Ready for changes
/Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/q/q.js:155
                throw e;
                ^

TypeError: qfs.isDirectory is not a function
    at /Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/customize-watch/lib/watcher.js:43:22
    at Array.map (<anonymous>)
    at /Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/customize-watch/lib/watcher.js:39:18
    at /Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/lodash/index.js:2046:14)
    at /Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/lodash/index.js:3346:13)
    at /Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/customize-watch/lib/watcher.js:35:7
    at _fulfilled (/Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/q/q.js:854:54)
    at /Users/ben/.nvm/versions/node/v10.16.3/lib/node_modules/bootprint/node_modules/q/q.js:883:30
BenMBP:bootprint-json-schema ben$
```

This function was added in m-io v0.5.0 (https://github.com/nknapp/m-io/commit/932d674b10167072438a21695049a7011b9da237) and while I tried to fix this with sufficient cloning of various bootprint repos, and editing various `package.json` files, I simply ran out of talent.

Most of the dependencies declare that they require `m-io 0.3.1` but clearly `customise-watch` requires `0.5.0` however, the `customize-watch` that gets installed declares that it requires `0.3.1`. 

I've raised this here, rather than at `bootprint/customize-watch` because I found this issue here and it doesn't appear to happen in the `bootprint` tests (I checked this too).

**Comment by nknapp** [comment]
I have published new versions of the packages using m-io. The use all 0.5.0 now. 
As far as I can tell, it works again now...

The problem is that I wanted ot get started with a new version a couple of years ago, but stopped in the middle of everything (for various private reasons). Some packages are now `3.0.1` like `customize`, but `bootprint@1` still uses `customize@1`.  I guess that was the reason for you to give up in the end.

In the end, it was a mistake to create so many small packages.

**Comment by puremourning** [comment]
Thanks so much, it's all working now ! Truly appreciate the work on this project.
